from pydantic import BaseModel

class BankRisk(BaseModel): 
    SK_ID_CURR : int
    EXT_SOURCE_3 : float
    BURO_CREDIT_TYPE_Creditcard_MEAN : float
    EXT_SOURCE_2 : float
    PREV_PRODUCT_COMBINATION_CashXSelllow_MEAN : float
    PREV_PRODUCT_COMBINATION_CashStreethigh_MEAN : float
    BURO_CREDIT_TYPE_Microloan_MEAN : float
    APPROVED_RATE_DOWN_PAYMENT_MAX : float
    PREV_CODE_REJECT_REASON_HC_MEAN : float
    FLAG_DOCUMENT_3 : float
    APPROVED_AMT_ANNUITY_MEAN : float
    APPROVED_HOUR_APPR_PROCESS_START_MEAN : float
    BURO_CREDIT_TYPE_Mortgage_MEAN : float
    APPROVED_DAYS_DECISION_MEAN : float
    PREV_AMT_ANNUITY_MIN : float
    DEF_30_CNT_SOCIAL_CIRCLE : float
    BURO_CREDIT_TYPE_Carloan_MEAN : float
    PREV_AMT_ANNUITY_MEAN : float
    DEF_60_CNT_SOCIAL_CIRCLE : float
    APPROVED_AMT_ANNUITY_MAX : float
    PREV_PRODUCT_COMBINATION_CashXSellhigh_MEAN : float
    PREV_RATE_DOWN_PAYMENT_MAX : float
    NAME_EDUCATION_TYPE_Secondarysecondaryspecial : float
    PREV_NAME_SELLER_INDUSTRY_Connectivity_MEAN : float
    PREV_CHANNEL_TYPE_APCashloan_MEAN : float
    PREV_CNT_PAYMENT_SUM : float
    PREV_NAME_CONTRACT_TYPE_Consumerloans_MEAN : float
    PREV_NAME_CONTRACT_TYPE_Revolvingloans_MEAN : float
    NAME_INCOME_TYPE_Pensioner : float
    PREV_NAME_CONTRACT_STATUS_Refused_MEAN : float
    PREV_CODE_REJECT_REASON_XAP_MEAN : float
    PREV_PRODUCT_COMBINATION_POSindustrywithinterest_MEAN : float
    PREV_CODE_REJECT_REASON_SCOFR_MEAN : float
    BURO_CREDIT_ACTIVE_Closed_MEAN : float
    OCCUPATION_TYPE_Drivers : float
    REGION_POPULATION_RELATIVE : float
    DAYS_BIRTH : float
    DAYS_EMPLOYED : float
    POS_MONTHS_BALANCE_SIZE : float
    DAYS_ID_PUBLISH : float
    DAYS_EMPLOYED_PERC : float
    ORGANIZATION_TYPE_Selfemployed : float
    BURO_DAYS_CREDIT_MEAN : float
    BURO_DAYS_CREDIT_MIN : float
    POS_COUNT : float
    REGION_RATING_CLIENT_W_CITY : float
    INSTAL_DAYS_ENTRY_PAYMENT_MEAN : float
    INSTAL_DAYS_ENTRY_PAYMENT_SUM : float
    CODE_GENDER : float
    BURO_CREDIT_ACTIVE_Active_MEAN : float
    REG_CITY_NOT_LIVE_CITY : float
    AMT_GOODS_PRICE : float
    PREV_NAME_CONTRACT_STATUS_Approved_MEAN : float
    PREV_DAYS_DECISION_MEAN : float
    ORGANIZATION_TYPE_Military : float
    ORGANIZATION_TYPE_School : float
    ORGANIZATION_TYPE_Transporttype3 : float
    PREV_NAME_PAYMENT_TYPE_XNA_MEAN : float
    PREV_CNT_PAYMENT_MEAN : float
    WALLSMATERIAL_MODE_Panel : float
    PREV_DAYS_DECISION_MIN : float
    PREV_RATE_DOWN_PAYMENT_MEAN : float
    PREV_AMT_GOODS_PRICE_MAX : float
    PREV_APP_CREDIT_PERC_MEAN : float
    ANNUITY_INCOME_PERC : float
    PAYMENT_RATE : float
    PREV_AMT_APPLICATION_MIN : float
    BURO_DAYS_CREDIT_MAX : float
    BURO_DAYS_CREDIT_ENDDATE_MIN : float
    BURO_AMT_CREDIT_SUM_LIMIT_SUM : float
    BURO_CREDIT_TYPE_Consumercredit_MEAN : float
    BURO_MONTHS_BALANCE_SIZE_SUM: float 
    PREV_AMT_CREDIT_MAX : float
    PREV_NAME_YIELD_GROUP_low_action_MEAN : float
    PREV_CODE_REJECT_REASON_LIMIT_MEAN : float
    INSTAL_DBD_MEAN : float
    APPROVED_CNT_PAYMENT_SUM : float
    POS_MONTHS_BALANCE_MEAN : float
    POS_SK_DPD_MAX : float
    POS_NAME_CONTRACT_STATUS_Active_MEAN : float
    POS_NAME_CONTRACT_STATUS_Completed_MEAN : float
    POS_NAME_CONTRACT_STATUS_Returnedtothestore_MEAN : float
    INSTAL_DPD_MAX : float
    INSTAL_DBD_MAX : float
    INSTAL_DBD_SUM : float
    PREV_NAME_TYPE_SUITE_nan_MEAN : float
    INSTAL_PAYMENT_DIFF_MAX : float
    INSTAL_PAYMENT_DIFF_MEAN : float
    INSTAL_PAYMENT_DIFF_SUM : float
    INSTAL_AMT_INSTALMENT_MEAN : float
    INSTAL_AMT_PAYMENT_MIN : float
    INSTAL_AMT_PAYMENT_MAX : float
    INSTAL_AMT_PAYMENT_MEAN : float
    INSTAL_DAYS_ENTRY_PAYMENT_MAX : float
    APPROVED_DAYS_DECISION_MAX : float
    APPROVED_DAYS_DECISION_MIN : float
    APPROVED_HOUR_APPR_PROCESS_START_MAX : float
    APPROVED_HOUR_APPR_PROCESS_START_MIN : float
    PREV_NAME_GOODS_CATEGORY_Furniture_MEAN : float
    PREV_NAME_GOODS_CATEGORY_XNA_MEAN : float
    PREV_NAME_PORTFOLIO_Cards_MEAN : float
    PREV_NAME_PORTFOLIO_POS_MEAN : float
    PREV_NAME_PORTFOLIO_XNA_MEAN : float
    PREV_NAME_PRODUCT_TYPE_walkin_MEAN : float
    PREV_CHANNEL_TYPE_Channelofcorporatesales_MEAN : float
    PREV_NAME_YIELD_GROUP_XNA_MEAN : float
    PREV_NAME_YIELD_GROUP_high_MEAN : float
    ORGANIZATION_TYPE_BusinessEntityType3 : float
    PREV_NAME_YIELD_GROUP_low_normal_MEAN : float
    PREV_PRODUCT_COMBINATION_CardStreet_MEAN : float
    PREV_PRODUCT_COMBINATION_CashStreetlow_MEAN : float
    PREV_PRODUCT_COMBINATION_POSmobilewithinterest_MEAN : float
    APPROVED_AMT_APPLICATION_MEAN : float
    APPROVED_AMT_CREDIT_MAX : float
    APPROVED_APP_CREDIT_PERC_MIN : float
    ORGANIZATION_TYPE_Construction : float
    INSTAL_COUNT : float
    NAME_INCOME_TYPE_Working : float
    DAYS_LAST_PHONE_CHANGE : float
    REGION_RATING_CLIENT : float
    FLAG_DOCUMENT_18 : float
    LIVE_CITY_NOT_WORK_CITY : float
    OCCUPATION_TYPE_Accountants : float
    FLAG_WORK_PHONE : float
    FLAG_EMP_PHONE : float
    OCCUPATION_TYPE_Laborers : float
    NAME_CONTRACT_TYPE_Revolvingloans: float
    DAYS_REGISTRATION: float
    NAME_EDUCATION_TYPE_Highereducation: float
    AMT_ANNUITY: float
    AMT_CREDIT: float
    NAME_FAMILY_STATUS_Married : float
    FLAG_OWN_CAR : float